### ISSUE TITLE
Minification: uuid.min.js

### ISSUE THREAD

**Issue by alexsanzdev** [kelektiv/node-uuid#103]
A minified version would be nice to have...
For the third-party libs in our web application, we use the minified version in the production deployment.

Thanks for a great lib!
/Alex

**Comment by broofa** [comment]
[Serious]  Alex, do you rely on every 3rd-party project to provide a minified version for you?  Also, do you minify your project code?

I ask because in my experience if a project gets to the point where minification is a concern, it gets done as part of the project build or deploy process.  So having one here adds little value, and just clutters up the code base.   At least, that's the rational I've had for not providing a minified version here. :-/

**Comment by AlexSanchezSTHLM** [comment]
Yes, all of the 3rd-party libs we use are already minified, and that's what we use currently, because we assume that the minified versions are tested as well by the providers. And we don't know if the libs can be minified without issues using the default minification options. So the answer is no, we don't minify those - only our own code. but I guess we could minify this one as well.
