### ISSUE TITLE
Option to remove dashes

### ISSUE THREAD

**Issue by 8bitjoey** [kelektiv/node-uuid#177]
Sometimes there is a requirement to get 32 character UUID (may be I shouldn't call that UUID :) ).
However the UUID generated by this library is 36 chars length. Because of dashes.

Is it possible to add an option to omit dashes? Something like this:

```
function v4(options, buf, offset) {
    ...
    return buf || bytesToUuid(rnds, 0, options.nodash);
}
```

```
function bytesToUuid(buf, offset, nodash) {
  var i = offset || 0;
  var bth = byteToHex;
  return  bth[buf[i++]] + bth[buf[i++]] +
          bth[buf[i++]] + bth[buf[i++]] + (nodash ? '' : '-') +
          ...
}
```

**Comment by broofa** [comment]
The dashes are part of the RFC4122 spec:

```
The formal definition of the UUID string representation provided by the following ABNF [7]:

      UUID                   = time-low "-" time-mid "-"
                               time-high-and-version "-"
                               clock-seq-and-reserved
                               clock-seq-low "-" node
```

If you need to remove them, `uuid().replace(/-/g, '')` should do the trick.

**Comment by broofa** [comment]
@LeoDupont: I have zero interest supporting non-standard id formats.

**Comment by jakesyl** [comment]
Just to add to this, this might be useful for downstream client libraries like [express-request-id](https://github.com/floatdrop/express-request-id) which allow users to pass params to `uuid`

**Comment by ctavan** [comment]
@jakesyl to re-iterate: This library focuses on what's covered by [RFC4122](https://tools.ietf.org/html/rfc4122), we have no interest in supporting non-standard formats.

If you are looking for more compact unique identifiers to be used in URLs and don't need UUID compliance you could look into some of the alternatives:

* [nanoid](https://github.com/ai/nanoid)
* [flake-id](https://github.com/T-PWK/flake-idgen)
* [cuid](https://github.com/ericelliott/cuid)
* [ulid](https://github.com/ulid/spec)

The fact that some of these libraries use base64 encoding instead of hex encoding allows them to encode the same amount of entropy in shorter strings which can be handy when storing & using IDs as opaque strings.
