### ISSUE TITLE
comment in first line

### ISSUE THREAD

**Issue by iofirag** [kelektiv/node-uuid#272]
hi,
line number 1 in `node-uuid/bin/uuid`
gives my compiler the error:
> SyntaxError: Unexpected character '#' (1:0)

so maybe you can change it 
from:
`#!/usr/bin/env node` 

to:
`// /usr/bin/env node` 

because it's not valid comment in js file as you know.

**Comment by broofa** [comment]
It's the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)), and is standard practice.  See https://stackoverflow.com/questions/20638520/appropriate-hashbang-for-node-js-scripts/28646724#28646724

If you're getting a syntax error, there's something wrong in your node setup.  The `node` interpreter has been shebang-aware since at least v0.12.
