### ISSUE TITLE
Error on IE 11

### ISSUE THREAD

**Issue by onoufriosm** [kelektiv/node-uuid#316]
I'm getting an error on IE 11 (Windows 7 specifically).

The error as shown on bugsnag:

![image](https://user-images.githubusercontent.com/12834779/59825564-08b6da00-933d-11e9-8c75-397adfed9875.png)

Using latest version 3.3.2

**Comment by broofa** [comment]
What error?

**Comment by jandom** [comment]
Sorry for not being more clear @broofa, there error is 

> Invalid argument.

All events we're seeing are identical: coming from Windows 7 + IE 11 version 11.0.0 combo

**Comment by jonkoops** [comment]
@onoufriosm @jandom do you have a snippet of code that produces the same exception in order to reproduce this?

**Comment by robwierzbowski** [comment]
We're seeing this error in a production app as well. Our implementation is just calling the UUID v4 function.

91% of errors are on IE11 and Windows 7. The rest are on Windows 8.1 and Windows Phone 8.1. 

It does not occur for all of our IE11, Windows 7 users. I can't reproduce in Browserstack.

The app has a userbase of a couple million people a month, would be happy to test any fixes in production.

**Comment by broofa** [comment]
FWIW, I (again) tested this with a basic webpack-ed test page - http://broofa.com/tests/uuid/ - using Windows 10 + IE11 (via browserling.com) and it's working as expected.

Any chance this is caused by a polyfill of some sort?   E.g. Googling around I found https://github.com/ionic-team/stencil/issues/1668 ... which mentions possible issues with  `core-js`'s UInt8Array polyfill.  Possibly related?

**Comment by jonkoops** [comment]
@broofa I think closing this is a bit premature. The issue seems to occur only with the combination of Windows 7 and Internet Explorer 11 and not on Windows 10.

This makes sense because Microsoft actually ships a different build of Internet Explorer 11 on each version of Windows, so there can be discrepancies between them. I would suggest to try and reproduce this issue with the combination of Internet Explorer 11 on Windows 7.

**Comment by broofa** [comment]
@jonkoops Win 7 + IE 11 is working for me.    This is using webpack to build the test at http://www.broofa.com/tests/uuid_test/, and running on BrowserStack.  I know @robwierzbowski said he's unable to reproduce in BrowserStack, however it's the only testing environment I have available to me at this time.

As stated before, until there's an SSCCE this isn't actionable.

![image](https://user-images.githubusercontent.com/164050/71594768-086a7900-2aee-11ea-876f-6a9ff0eeabe8.png)

**Comment by jonkoops** [comment]
@broofa If it's not reproducible, then it cannot be fixed. Thanks for giving it another look!

**Comment by broofa** [comment]
>  If it's not reproducible, then it cannot be fixed.

@onoufriosm, @jandom, @robwierzbowski or whoever is welcome to submit a PR.  It just needs to come from someone who can explain the nature of the problem and fix.  And, more importantly, verify the fix works (and also that it won't break something else.)

**Comment by robwierzbowski** [comment]
The difficulty we had in reproducing is that it only happens on a subset of Win 7 + IE11 browsers. Not sure if it's based on something installed in the browser, a race condition, or a specific Win 7 minor version. 

None of the environments I have to test on can reproduce the problem. I posted in the hopes that others might be able to.

We probably won't put more effort into reproducing this since the number of users affected is pretty low. Thanks for taking a look Broofa and everyone else.

**Comment by ASliceOfLife** [comment]
I came across the same error by using crypto-js. And for me it looks like it is linked to a specific patch level of Win7. Because i can reproduced it on a test VM i was provided with, which is not up to date. On a local VBox image, which is up2date, i was not able to reproduce the behavior.

**Comment by ctavan** [comment]
Thank you for the Info @ASliceOfLife 

However, this library will definitely not try to support specific legacy Windows 7 versions. Quite the opposite, I‘m happy to provide another reason for people to get rid of Windows 7 😉

**Comment by jandom** [comment]
Never expected to see this one come back to life, very impressed that @ASliceOfLife actually managed to track it down! @onoufriosm check this out
