### ISSUE TITLE
TypeScript rewrite?

### ISSUE THREAD

**Issue by ctavan** [kelektiv/node-uuid#334]
@defunctzombie suggested in [this comment](https://github.com/kelektiv/node-uuid/issues/330#issuecomment-541727301) that the node-uuid module could be re-written in TypeScript.

What would be the benefits of such a rewrite over modern JavaScript?

**Comment by broofa** [comment]
It should be noted that the reason for this is to simplify support of ES modules in browsers and Node, not because TS is particularly well-suited to generating UUIDs per se.

 I'm typically not a fan of Typescript for OpenSource projects. It complicates the toolchain and makes projects less approachable.

**Comment by defunctzombie** [comment]
(opinion) type information has made my development more pleasant and proficient - but I also understand not wanting to take on the additional build step or barrier for other developers. Typescript has let me use one toolchain to build rather than collecting a bunch of babel plugins like I would need to do before. The API surface is the uuid module is sufficiently small and often "obvious" in a way that it itself won't benefit all that much. Like with most things - it is just preference. I've found that where I use to favor plain JS and no build step - that with new tooling the build "step" doesn't get in the way of my iteration.

Practically - I don't consider my comment of porting to TS as something that would actually happen but threw it out there anyway - hopefully without it becoming a distraction to your work.

**Comment by ctavan** [comment]
Thanks! I still think that, given the broad adoption of TypeScript especially in application development, offering useful type definitions through `@types/uuid` should be a priority of this repository as well and I will work on that (#328).

For TypeScript users this should hopefully already provide most of the benefits.

**Comment by dstaley** [comment]
As a TypeScript user who uses the `node-uuid` package, my main desire is having types included with the package as opposed to downloading the `@types/uuid` package. I would prefer the library be written in TypeScript since that guarantees that the types match the behavior of the library, but I completely understand the hesitation there. I wrote a [RFC for a TypeScript migration](https://github.com/Kinto/kinto.js/issues/999) for the libraries I work on, and all of its points are equally applicable here. I'm actually of the opinion that TypeScript encourages outside contributors since it gives another layer of checks over their code. Think of it like an extra set of unit tests. In Kinto we use TypeScript to generate an ES-modules build and a CommonJS build, and then use Rollup to generate a browser-friendly ES-modules build alongside a traditional UMD build.

I'm also a big fan of using the TypeScript compiler in lieu of Babel even in pure JavaScript projects. TypeScript's inference is pretty great, so it can catch some errors even without any types. You can improve the quality of the checks by adding JSDoc formatted comments.

**Comment by sam-s4s** [comment]
Yes, having types included would be great. Also an important request - please make sure that `@types/node` is not being pulled in. It really ruins a project. I can't use the `@types/uuid` package at present because it pulls the node types in, and then you can't use things like `setTimeout` properly, because the non-browser, node versions of the types get pulled into your project, creating chaos :(

**Comment by broofa** [comment]
Let's close this - I think this is covered by #328

**Comment by ctavan** [comment]
OK, we'll first make sure to get the typings in order, see #328. Should not matter if the uuid code base itself is written in TypeScript or not as long as we provide useful typings.

**Comment by jamiehaywood** [comment]
I know this was closed almost 2 years ago, but I wanted to see if there had been any change in thoughts around the TS rewrite? I think it would be an awesome step forward for developer experience using this library, as mentioned above.

**Comment by LinusU** [comment]
I personally love TypeScript, but still doesn't think that it's the right fit for this project. Since the codebase is so simple, I don't think that there is that much to be gained by switching to TS.

If anything, I think that we should consider dropping both Babel & Rollup and only ship an ESM version in the next major version. All the currently supported versions of Node.js now supports ESM, and not having any build step at all I think is something that makes the setup even more simple, which makes the project more approachable for contributors! 🚀

**Comment by piranna** [comment]
> I think that we should consider dropping both Babel & Rollup and only ship an ESM version in the next major version.

Agree.

**Comment by dstaley** [comment]
> I think that we should consider dropping both Babel & Rollup and only ship an ESM version in the next major version.

I would caution against this since the ecosystem hasn't caught up to ESM, and publishing an ESM-only package as low-level as uuid can cause significant breakage in applications (in fact, you're unable to synchronously import ESM-only packages in CJS environments like node). If uuid does decide to move to ESM-only, I'd strongly recommend maintaining the current major version with features/bug fixes until ESM support is more wide spread.

**Comment by broofa** [comment]
> All the currently supported versions of Node.js now supports ESM

This may be true for [nodejs.org's support matrix](https://nodejs.org/en/about/releases/), but at this time we (`uuid`) still support [node 8+](https://github.com/uuidjs/uuid/blob/master/.github/workflows/ci.yml#L12) and [IE 11](https://github.com/uuidjs/uuid/blob/master/wdio.conf.js#L22-L26).

It's important to remember that the webpack and rollup builds were added to allow for CI testing (in both node and in the browser) which was one of the more important improvements to the stability and quality of this project.

**Comment by piranna** [comment]
> we (`uuid`) still support [node 8+](https://github.com/uuidjs/uuid/blob/master/.github/workflows/ci.yml?rgh-link-date=2021-09-14T01%3A17%3A19Z#L12) and [IE 11](https://github.com/uuidjs/uuid/blob/master/wdio.conf.js?rgh-link-date=2021-09-14T01%3A17%3A19Z#L22-L26)

But they don't have support from their maintainers... Why we should support them?

**Comment by LinusU** [comment]
> > All the currently supported versions of Node.js now supports ESM
> 
> This may be true for [nodejs.org's support matrix](https://nodejs.org/en/about/releases/), but at this time we (`uuid`) still support [node 8+](https://github.com/uuidjs/uuid/blob/master/.github/workflows/ci.yml#L12) and [IE 11](https://github.com/uuidjs/uuid/blob/master/wdio.conf.js#L22-L26).

Yes, my comment was a bit off since we don't actually use rollup to produce the build, my bad.

However, we currently ship three builds in the final package: CommonJS, ESM for Node, ESM for browsers. My proposal is to drop the CommonJS build, since e.g. IE 11 doesn't support CommonJS either.

Not saying that there is any stress in doing this, just that it would be nice to do it the next time we release a major release/drop support for older versions of Node.js ☺️

**Comment by defunctzombie** [comment]
This issue is closed because the current maintainers are not pursuing or entertaining this effort at this time. If someone wants to come along and move @types/uuid into this module via a PR or propose a typescript version that is up to them to consider contributing and then making the case for their new version over the status quo.
