### ISSUE TITLE
IDs sequenced by time?

### ISSUE THREAD

**Issue by binarykitchen** [kelektiv/node-uuid#75]
Hi there

I'm using `uuid.v1()` for keys within my LevelDB + node.js app. Whenever I list entries from the LevelDB, the sorting happens by these keys and unfortunately it is very random.

I mean, in a boring relational DB you increment the primary keys. Whenever you query the rows, the are sorted by these primary keys as a default behavior. This is good, you always know that recently inserted rows appear on top.

But with UUIDs v1 as keys, the sequence is pretty random.

Is there a solution for that? Do I need to fine-tune some options to achieve that behavior or can this be implemented at all in a new version?

**Comment by xerosanyam** [comment]
Hello guys,

`uuid.v4().replace(/^(.{8})-(.{4})-(.{4})/, '$3-$2-$1') < uuid.v4().replace(/^(.{8})-(.{4})-(.{4})/, '$3-$2-$1')`

doesn't always result in true.
what am I missing here ?

**Comment by broofa** [comment]
@xerosanyam, v4 uuids are randomly generated.

**Comment by xerosanyam** [comment]
So there is no way to sequence IDs by time ? :thinking:

**Comment by broofa** [comment]
Only for v1 (timestamped) uuids.  You'd have to lexicographically order by [`time_hi`, `time_mid`, `time_lo`, and `clock_sequence` fields](https://github.com/kelektiv/node-uuid/blob/master/v1.js#L69-L89), respectively. 

```
const uuidV1 = require('uuid/v1');

function v1UuidCompare(a, b) {
  a = a.replace(/^(.{8})-(.{4})-(.{4})-(.{4})/, \'$4-$3-$2-$1\');
  b = b.replace(/^(.{8})-(.{4})-(.{4})-(.{4})/, \'$4-$3-$2-$1\');
  return a < b ? -1 : (a > b ? 1 : 0);
}

> v1UuidCompare(uuidV1(), uuidV1())
-1
```

**Comment by sm2017** [comment]
@broofa Why you have 2 logic?
```js
replace(/^(.{8})-(.{4})-(.{4})-(.{4})/, \'$4-$3-$2-$1\')
```
and
```js
replace(/^(.{8})-(.{4})-(.{4})/, '$3-$2-$1')
```

**Comment by broofa** [comment]
@sm2017:  Good question.

I edited my last comment to remove the four field form (the one that resulted in `clockseq` being the primary sort field).  Readers should just stick to the `replace(/^(.{8})-(.{4})-(.{4})/, '$3-$2-$1')` form.

While an argument can be made for including `clockseq` in the sort order because it gets incremented if there's a system clock regression, the fact it is randomly initialized on process startup makes it unsuitable for inclusion in sorting.   (Including it in my previous comment was a mistake on my part.  My apologies for the confusion.)

What this means is that in the (very rare?) case where the system clock regresses (goes back in time), the sort order won't reflect the order in which ids were generated.  I expect that's a minor concern for most folks, however.

(Note: The behavior of `clockseq` described here is part of the 4122 spec, where the intent is to minimize the risk of uuid collisions.)

**Comment by sm2017** [comment]
@broofa Thanks a lot

**Comment by jonagoldman** [comment]
In RFC 4122 UUID v1 format, the first three number groups `aaaaaaaa-bbbb-cccc` are generated from the low, middle, and high parts of a timestamp.

So I think it's possible to transform a UUID v1 to an **ordered** UUID v1 and back like this:

```js
const uuidV1 = require('uuid/v1');

function orderUUIDv1(regularUuid) {
	return regularUuid.replace(/^(.{4})(.{4})-(.{4})-(.{4})/, '$4$3-$1-$2');
}

function unorderUUIDv1(orderedUuid) {
	return orderedUuid.replace(/^(.{4})(.{4})-(.{4})-(.{4})/, '$3$4-$2-$1');
}

// a9ec5a07-e872-11e9-b92c-080027d0eccd
let regularUuid = uuidV1();

// 11e9e872-a9ec-5a07-b92c-080027d0eccd
let orderedUuid = orderUUIDv1(regularUuid);

// a9ec5a07-e872-11e9-b92c-080027d0eccd
let unorderedUuid = unorderUUIDv1(orderedUuid);

```

This works by swapping the `time-low` and `time-high` parts (the first and third groups of hexadecimal digits, respectively). Basically moving the more rapidly varying part to the right.

This is inspired by how [MySQL 8 deals with UUIDs](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid). Specifically [UUID_TO_BIN](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_uuid-to-bin) and [BIN_TO_UUID](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_bin-to-uuid), and explained [here](https://mysqlserverteam.com/mysql-8-0-uuid-support/).

**Comment by broofa** [comment]
> So I think it's possible to transform a UUID v1 to an **ordered** UUID v1 and back like this:

Just so we're clear, there is no provision in RFC4122 for "ordered" v1 UUIDs.  Describing them as such is a misnomer.   (In fact, the transformation described creates an explicitly _invalid_ UUID, because it moves the `version` field as well as the `time_hi` field)

Better to just say "transform a v1 UUID to a sort-friendly string"

**Comment by jonagoldman** [comment]
@broofa Yes, the result is an invalid UUID string, but it can be used to store it in an optimized way in relational databases, specially MySQL.

Main disadvantages of storing regular UUIDs are:

1) UUID is not ordered, so inserts are random and the data is scattered.
	- Fixed by transforming it to a 'sort-friendly string'.
2) UUID has 36 characters which make it bulky. When used as a PRIMARY KEY it makes the index bigger which sometimes cannot fit into memory.
	- Fixed by storing it in BINARY.

The fact that the [MySQL added this functionality in MySQL 8](https://mysqlserverteam.com/mysql-8-0-uuid-support/) is a good indicator that it is useful.

Of course there is **no need to do it JavaScript**, you can transform to ordered UUIDs in MySQL or PHP, but I post it here in case it is helpful to anyone.

**Comment by bradennapier** [comment]
FYI I built this awhile back which does this shuffling when converting `uuidv1` into a binary format: https://github.com/odo-network/binary-uuid

**Comment by rajatkeshar** [comment]
Hi, is there any ways to generate uuid in descending order?

**Comment by ctavan** [comment]
What exactly are you trying to achieve, @rajatkeshar ?

**Comment by jonagoldman** [comment]
I think he means a version 1 UUID with the time fields swapped so the lowest bytes appear first, the middle bytes are next, and the highest bytes come last so that the UUID is sorted by creation time.

Like in [Ramsey Orxered-Time UUID](https://uuid.ramsey.dev/en/latest/customize/ordered-time-codec.html#customize-ordered-time-codec)

Or maybe the experental UUID version 6...

**Comment by ctavan** [comment]
But generating these would still result in _ascending_ order…
